### ISSUE TITLE
Minify all JS files

### ISSUE THREAD

**Issue by fuerbringer** [fuerbringer/wired-startpage#3]
Currently `wired.js` is left out of the uglifying and watch process. It really makes no sense and should be fixed.

**Comment by fuerbringer** [comment]
Solved and implemented in #2.

**Comment by Hoi15A** [comment]
Not actually solved an implemented. Currently `wired.js` is still not being minified

**Comment by fuerbringer** [comment]
Got confused for a sec there. Alright. Anyways then we probably don't need [this](https://github.com/fuerbringer/wired-startpage/blob/master/data/config.json.example#L10) and [this](https://github.com/fuerbringer/wired-startpage/blob/master/views/layout.pug#L29) anymore (after we put it into the Gruntfile).

**Comment by fuerbringer** [comment]
Solved in https://github.com/fuerbringer/wired-startpage/commit/e51726a6fab9e729785c966c6eb4f8f8098e0929. That commit combines all JS files into `master.min.js` and CSS files into `master.min.css`.
